import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { LeaseIdError, LeaseIdErrorCodes } from '@/application';

import { LeaseIdGenerationError, UuidV7LeaseIdGenerator } from './uuid-v7-lease-id-generator';

describe('UuidV7LeaseIdGenerator', () => {
  it('returns the identity generated by its configured source', () => {
    const leaseId = '0198f334-6dc5-7c20-9af1-91d7e599c001';

    assert.equal(new UuidV7LeaseIdGenerator(() => leaseId).generate(), leaseId);
  });

  it('classifies a source failure and preserves its cause', () => {
    const cause = new Error('source details');
    const generator = new UuidV7LeaseIdGenerator(() => {
      throw cause;
    });

    assert.throws(
      () => generator.generate(),
      (error: unknown) => error instanceof LeaseIdGenerationError && error.cause === cause,
    );
  });

  it('rejects an invalid identity returned by the configured source', () => {
    const generator = new UuidV7LeaseIdGenerator(() => '550e8400-e29b-41d4-a716-446655440000');

    assert.throws(
      () => generator.generate(),
      (error: unknown) =>
        error instanceof LeaseIdGenerationError &&
        error.cause instanceof LeaseIdError &&
        error.cause.code === LeaseIdErrorCodes.Invalid,
    );
  });
});
